export const questionItems = [
  "I tend to face my fears",
  "I often check my work over repeatedly to find any mistakes",
  "I think that I am entitled to more respect than the average person is",
  "I do only the minimum amount of work needed to get by.",
  "I am an ordinary person who is no better than others.",
  "If I am worried or anxious about something, I will do or face it anyway.",
  "I wouldn't want people to treat me as though I were superior to them.",
  "I see myself as critical, quarrelsome",
  "I tend to manipulate others to get my way",
  "I see myself as sympathetic, warm.",
  "Even if I feel terrified, I will stay in the situation until I have done what I need to do...",
  "I tend to exploit others towards my own end.",
  "I see myself as disorganized, careless.",
  "I often push myself very hard when trying to achieve a goal.",
  "I have used flattery to get my way",
  "If there is an important reason to face something that scares me, I will face it.",
  "I see myself as dependable, self-disciplined.",
  "I have used deceit or lied to get my way.",
  "I will do things even though they seem to be dangerous",
  "I will stand up for what I believe is right, even if it causes a ruckus.",
];

export const questionsMapping = {
  0: "Gryffindor",
  1: "Ravenclaw",
  2: "Slytherin",
  3: "Hufflepuff",
  4: "Hufflepuff",
  5: "Gryffindor",
  6: "Hufflepuff",
  7: "Ravenclaw",
  8: "Slytherin",
  9: "Hufflepuff",
  10: "Gryffindor",
  11: "Slytherin",
  12: "Ravenclaw",
  13: "Ravenclaw",
  14: "Slytherin",
  15: "Gryffindor",
  16: "Ravenclaw",
  17: "Slytherin",
  18: "Gryffindor",
  19: "Hufflepuff",
};

